### ISSUE TITLE
help

### ISSUE THREAD

**Issue by foehncyclone** [yitang1/yitangCalamity#1]
大佬，最近Fargo's Souls x Calamity Compatibility那个mod的作者把他的mod从创意工坊中删除了，请问您是否有原版mod，如果有的话能不能麻烦您给我发一份，我的邮箱是3497627208@qq.com

**Comment by yitang1** [comment]
很遗憾我没有备份那个mod的文件，不过那个mod在github有开放源码→[这里](https://github.com/vodavodochka/FargoCalamity)，你可以自己去下载编译。

**Comment by foehncyclone** [comment]
明白了，多谢




焚之为灰矣
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yitang1/yitangCalamity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月20日(星期六) 晚上8:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yitang1/yitangCalamity] help (Issue #1)





 
很遗憾我没有备份那个mod的文件，不过那个mod在github有开放源码→这里，你可以自己去下载编译。
